name: Update
on:
  repository_dispatch:
    types: [ build-success ]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update image tag
        run: |
          sed -i "s|newTag: .*|newTag: ${{ github.event.client_payload.image_tag }}|" base/kustomization.yaml

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update image to ${{ github.event.client_payload.image_tag }}"
          git push
